site_name: techNotes
nav:
  - Home: index.md
  - Linux:
    - General: Linux/index.md
    - Laptops:
      - Ubuntu: Linux/ubuntu.md
      - Application Software: Linux/software.md
      - Command-line Tools: Linux/tools.md
      - Shell Scripts: shell/index.md
      # - Upgradation: Linux/upgrade.md
      - WSL: Linux/wsl.md
    - Servers: 
      - General: Linux/servers.md
      - AliECS: Linux/ecs.md
      - Rocky-Linux: Linux/rocky-server.md
      - G40: Linux/asAserver.md 
    - CHPC-Cluster:
      - Tips: Linux/chpc.md
      - Blog:
        - Fail to SSH passwordlessly: Linux/blog/2020-12-17-passwordless-failed.md
        - Fail to Access Home: Linux/blog/2021-05-12-fail-to-access-home.md
        - Why Job Restart?: Linux/blog/2022-11-19-why-job-restart.md
  - StatProgramming:
    - Comparisons: comparisons/stat.md
    - R:
      - Base: R/index.md
      - Plot: R/plot.md
      - Blog:
        - ggplot2 中的 legend: R/legend_from_zhihu.md
        - new sample function (v3.6.0+): R/sample.md
        - 一道与 factor 有关的问题: R/factor.md
    - Python:
      - Base: python/index.md
      - Conda: python/conda.md
      - OpenCV: python/opencv.md
      - rpy2: python/rpy2.md
      - Blog:
        - PyStan 体验: python/pystan/README.md
        - 自建关键词索引页: python/esltag.md
    - Julia: 
      - Base: julia/index.md
      - Plot: julia/plot.md
    - Matlab: 
      - Base: Matlab/index.md
  - CSProgramming:
    - C/C++: 
      - General: Cpp/index.md
      - Qt: Cpp/Qt/index.md
    - Java: java/index.md
    - SQL: 
      - General: SQL/index.md
      - RMySQL: R/install-notes-for-rmysql.md
    - Cuda: cuda/index.md
  - DocProgramming:
    - TeX:
      - General: TeX/index.md
      - TravisCI: TeX/CI.md
      - arXiv: TeX/arxiv.md
      - VarGreek: TeX/vargreek.md
      - Overleaf: TeX/overleaf.md
    - Markdown: 
      - General: doc/markdown.md
    - StaticPages:
      - Website: website/index.md
      - Disqus: website/disqus.md
      - CSS: website/css.md
      - JS: js/index.md
      - Analytics: website/analytics.md
    - DynamicPages:
      - PHP: PHP/index.md
      - XAMPP: website/xampp.md
  - Network/Internet:
    - 科学上网: Internet/sci-int.md
    - 一般问题: Internet/index.md
    - IPv6: Internet/ipv6.md
    - 加密算法: Internet/encrypt.md
  - Development:
    - Autotools: autotools/index.md
    - Docker: dev/docker.md
    - Git: Git/index.md
    - Phantomjs: phantomjs/index.md
  - Stat:
    - Probability: stats/prob.md
    - Statistics: stats/index.md
    - Scientific: scientific/index.md
    - Matrix: stats/matrix.md
  - InvitedPosts:
    - Samtools: biology/samtools.md
    - MaxClusterUsage: Linux/maximum-usage-of-ITSC-cluster-resource.md
  - Misc:
    - English: English/index.md
    - Guitar: guitar/index.md
    - Windows: win/index.md
    - Biology: biology/index.md
    - Finance: finance/index.md
    - Fresh: fresh/index.md
    - Links: links/index.md
    - Live: misc/live.md
    - 小程序: misc/wx.md
    - jssdk: misc/wxjssdk.md
    - 讲座: misc/report.md
    - Mi: mi/index.md
    - Terminology: misc/terms.md

theme:
  name: 'material'
  custom_dir: 'theme'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
google_analytics: ['UA-85007363-6', 'auto']
copyright: 'Copyright &copy; 2017-2022 weiya'
site_author: weiya
site_description: '技术博客'
site_url: https://tech.hohoweiya.xyz
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/szcf-weiya'
    - icon: 'fontawesome/solid/book'
      link: 'https://esl.hohoweiya.xyz'
    - icon: 'fontawesome/solid/house'
      link: 'https://hohoweiya.xyz'
    - icon: 'fontawesome/regular/newspaper'
      link: 'https://stats.hohoweiya.xyz'
    - icon: 'fontawesome/regular/note-sticky'
      link: 'https://blog.csdn.net/szcf715'
    - icon: 'fontawesome/regular/envelope'
      link: 'mailto:szcfweiya@gmail.com'

repo_name: 'szcf-weiya/techNotes'
repo_url: 'https://github.com/szcf-weiya/techNotes'
edit_uri: edit/master/docs/
extra_javascript:
  - javascripts/baiduzhanzhang.js
  - javascripts/extra.js
  - javascripts/mathjax.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
#extra_css:
    #  - stylesheets/extra.css
markdown_extensions:
  # https://github.com/mkdocs/mkdocs/issues/1678
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - meta
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
      lang: 
        - en
        - ja
  - git-revision-date-localized:
      enable_creation_date: true