site_name: techNotes
nav:
  - Home: index.md
  - Linux:
    - Linux/index.md
    - General: Linux/general.md
    - Command-line Tools: Linux/tools.md
    - Shell Scripts: shell/index.md
    - Laptops:
      - Ubuntu: Linux/ubuntu.md
      - Applications: Linux/software.md
      - G40: Linux/asAserver.md 
      # - Upgradation: Linux/upgrade.md
      - WSL: Linux/wsl.md
      - Blog:
        - CD in USB Drive: Linux/blog/2024-03-09-CD-drive.md
        - Portable SSD: Linux/blog/2020-08-25-PSSD.md
        - Charge Adaptively: Linux/blog/2020-09-01-charge-battery-adaptively.md
        - Switch Monitor Mode: Linux/blog/2021-06-07-switch-monitor.md
        - Use Old Kernel: Linux/blog/2021-07-28-use-old-kernel.md
    - Servers: 
      - General: Linux/servers.md
      - AliECS: Linux/ecs.md
      - Rocky-Linux @ Fan Group: Linux/rocky-server.md
      - CHPC-Cluster @ CUHK: Linux/chpc.md
      - Blog:
        - ipv6 on aws: Internet/ipv6.md
        - Fail to SSH pwdlessly: Linux/blog/2020-12-17-passwordless-failed.md
        - Fail to Access Home: Linux/blog/2021-05-12-fail-to-access-home.md
        - Why Job Restart?: Linux/blog/2022-11-19-why-job-restart.md
    - Network/Internet:
      - Internet/index.md
      - 科学上网: Internet/sci-int.md
      - 加密算法: Internet/encrypt.md

  - StatProgramming:
    - Comparisons: comparisons/stat.md
    - R:
      - Base: R/index.md
      - Plot: R/plot.md
      - Blog:
        - Install blipr on Yale HPC: R/blog/2024-02-13-blipr-yale-hpc.md
        - Legend in ggplot2: R/legend_from_zhihu.md
        - New sample function (v3.6.0+): R/sample.md
        - Speedup related to factor: R/factor.md
    - Python:
      - Base: python/index.md
      - Conda: python/conda.md
      - OpenCV: python/opencv.md
      - rpy2: python/rpy2.md
      - Blog:
        - 那些年抢过的讲座: misc/report.md
        - PyStan 体验: python/pystan.md
        - 自建关键词索引页: python/esltag.md
    - Julia: 
      - Base: julia/index.md
      - Plot: julia/plot.md
      - Dev: julia/dev_package.md
    - Matlab: 
      - Base: Matlab/index.md
    - SAS: SAS/index.md
  - CSProgramming:
    - C/C++: 
      - General: Cpp/index.md
      - Qt: Cpp/Qt/index.md
    - Java: 
      - java/index.md
    - SQL: 
      - SQL/index.md
      - RMySQL: R/install-notes-for-rmysql.md
    - CUDA: 
      - cuda/index.md
  - DocProgramming:
    - TeX:
      - General: TeX/index.md
      - TravisCI: TeX/CI.md
      - arXiv: TeX/arxiv.md
      - VarGreek: TeX/vargreek.md
      - Overleaf: TeX/overleaf.md
    - Markdown: 
      - General: doc/markdown.md
  - BuildWebsite:
    - website/index.md
    - Components:
      - CSS: website/css.md
      - JS: website/js.md
      - Disqus: website/disqus.md
      - Analytics: website/analytics.md
    - Static:
      - Jekyll: website/jekyll.md
    - Dynamic:
      - Shiny: website/2024-06-10-spinup-rshiny.md
      - PHP: website/php.md
      - XAMPP: website/xampp.md
      - 微信小程序: misc/wx.md
    - CDN: website/cdn.md
    - Others: 
      - 其它问题: website/general.md
      - jssdk: misc/wxjssdk.md
  - Development:
    - Autotools: autotools/index.md
    - Docker: dev/docker.md
    - Git: Git/index.md
    - Phantomjs: phantomjs/index.md
  - Stat:
    - Probability: stats/prob.md
    - Statistics: stats/index.md
    - Scientific: scientific/index.md
    - Matrix: stats/matrix.md
  - InvitedPosts:
    - Samtools: biology/samtools.md
    - MaxClusterUsage: Linux/maximum-usage-of-ITSC-cluster-resource.md
  - Misc:
    - English: English/index.md
    - Guitar: guitar/index.md
    - Windows: win/index.md
    - Biology: biology/index.md
    - Finance: finance/index.md
    - Fresh: fresh/index.md
    - Links: links/index.md
    - Live: misc/live.md
    - Mi: mi/index.md
    - Terminology: misc/terms.md

theme:
  name: 'material'
  custom_dir: 'theme'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.action.edit
  font: false
google_analytics: ['UA-85007363-6', 'auto']
copyright: 'Copyright &copy; 2017-2024 weiya'
site_author: weiya
site_description: '技术博客'
site_url: https://tech.hohoweiya.xyz
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/szcf-weiya'
    - icon: 'fontawesome/solid/book'
      link: 'https://esl.hohoweiya.xyz'
    - icon: 'fontawesome/solid/house'
      link: 'https://hohoweiya.xyz'
    - icon: 'fontawesome/regular/newspaper'
      link: 'https://stats.hohoweiya.xyz'
    - icon: 'fontawesome/regular/note-sticky'
      link: 'https://blog.hohoweiya.xyz'
    - icon: 'fontawesome/regular/envelope'
      link: 'mailto:szcfweiya@gmail.com'

repo_name: 'szcf-weiya/techNotes'
repo_url: 'https://github.com/szcf-weiya/techNotes'
edit_uri: edit/master/docs/
extra_javascript:
  - javascripts/baiduzhanzhang.js
  - javascripts/extra.js
  - javascripts/mathjax.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/custom.css
    #  - stylesheets/extra.css
markdown_extensions:
  # https://github.com/mkdocs/mkdocs/issues/1678
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - meta
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
      lang: 
        - en
        - ja
  - git-revision-date-localized:
      enable_creation_date: true